### ISSUE TITLE
(RPC) monitor blocks endpoint

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/tezos-ts#15]
As a developer

I want to be able to query the monitor block endpoint

In order to see last update to the Tezos network and update my application

**Comment by carte7000** [comment]
Some early observation

The monitor heads endpoint seems to return incomplete response ERR_INCOMPLETE_CHUNKED_ENCODING which prevent querying to the endpoint normally in browsers.

**Comment by jevonearth** [comment]
As discussed, let's build a standalone websocket server that will be an intermediary between the browser and the tezos-node.

The service will listen on monitor blocks, and the caller can listen on the websocket for particular operations.

We should document the websocket API properly, and in the README for the new service, we should state that "We hope that an embodiment of the API spec implemented in this service eventually gets implemented in the nomadic tezos-node directly, at which point we will be delighted to delete this code"
