### ISSUE TITLE
(RPC) getConstants

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/tezos-ts#3]
Add Interface and an RPC implementation for getting constants.

RPC API docs;
https://tezos.gitlab.io/tezos/api/rpc.html#get-block-id-context-constants

Example curl command;
`curl http://10.60.58.16:8732/chains/main/blocks/5/context/constants`
`curl http://10.60.58.16:8732/chains/main/blocks/head/context/constants`

- [ ] Implement interface
- [ ] Implement default rpc implementation for interface
- [ ] Implement type to represent constants 
- [ ] Add call to `examples/`

## Tentative description for API doc;

getConstants returns the economic constants for the given chain. Constants are constant in the context of a block. Constants were initialized in the genesis block and can only be changed by a Tezos protocol amendment. Constants are or can be different on mainnet, alphanet or other nets.

**Comment by progital** [comment]
@carte7000 clarified:

With regards to issue #3 I think it does not involve exposing it in the tezos-ts package yet. issue #3 would be to implement the getConstants function in the @tezos-ts/rpc package
```
import RpcClient from '@tezos-ts/rpc';
const client = new RpcClient();
client.getConstants();
```

**Comment by carte7000** [comment]
@jevonearth, @progital 

As per this document: https://gitlab.com/cryptiumlabs/tezos/blob/master/specs/migration_004_to_005.md

There is minor changes to this endpoint coming with the next Babylon_005

> There are two new constants at `context/constants` endpoint - `quorum_min` and `quorum_max`, both in centile of percentage (a fraction out of 10,000).

I suggest we create another issue so we handle that case for the new update that is coming
